
tasks:
  - command: curl lama.sh | sh -s -- -p 5555
  - command: curl lama.sh | sh -s -- -p 3002
  - command: curl lama.sh | sh -s -- -p 3003
  - command: curl lama.sh | sh -s -- -p 3004
  - command: curl lama.sh | sh -s -- -p 3005
  - command: curl lama.sh | sh -s -- -p 3006
 
ports:
  - port: 5555
    visibility: private
    onOpen: ignore
  - port: 3001
    onOpen: open-preview
    visibility: public
  - port: 3002
    onOpen: open-browser
    visibility: public  
  - port: 3003
    onOpen: notify

